Repository openshift/contra-hdsl, pull requests merged in 2018-10, with the labels that each got.

#54 ADD report HDSL method
  vars/report.groovy
  vars/report.txt
Labels: size/M

#58 Add reporting method
  vars/report.groovy
Labels: size/XS

#59 executeTests: use Elvis operator to avoid NPE
  vars/executeTests.groovy
Labels: bugfix, size/XS
