Repository openshift/contra-hdsl, pull requests merged in 2018-09, with the labels that each got.

#44 UPDATE url for repo and remove SSH mention
  README.md
Labels: size/XS

#47 Add Jenkins Slave s2i config for contra-hdsl
  config/s2i/jslave/jslave-buildconfig-temaplte.yaml
Labels: size/M

#48 Fixed name of template
  config/s2i/jslave/jslave-buildconfig-template.yaml
Labels: size/XS

#49 UPDATE createDslContainers to use jenkins slave
  README.md
  vars/createDslContainers.groovy
Labels: enhancement, size/S

#51 UPDATE README for imagestream deployment
  README.md
Labels: kind/documentation, size/S
