Repository openshift/contra-hdsl, pull requests merged in 2018-12, with the labels that each got.

#67 UPDATE documentation for withPod() var
  docs/source/withPod.rst
Labels: size/XS

#72 linchin -> linchpin
  vars/createDslContainers.groovy
Labels: needs-ok-to-test, size/XS

#73 always pull DSL images
  vars/createDslContainers.groovy
Labels: needs-ok-to-test, size/XS

#74 code contribution in README
  README.md
Labels: needs-ok-to-test, size/S

#75 Add ability to pull images from dockerhub easily.
  README.md
  docs/source/withHdslPod.rst
  docs/source/withPod.rst
  src/org/centos/contra/Infra/Defaults.groovy
  src/org/centos/contra/Infra/Utils.groovy
  vars/withHdslPod.groovy
  vars/withHdslPod.txt
  vars/withPod.groovy
Labels: size/L

#76 UPDATE documentation to use Contra HDSL
  README.md
  vars/configureInfra.txt
  vars/createDslContainers.txt
  vars/destroyInfra.txt
  vars/executeTests.txt
  vars/parseConfig.txt
Labels: size/M
