Repository openshift/contra-hdsl, pull requests merged in 2019-04, with the labels that each got.

#84 Fixes env variable calls and increases testability of sh calls
  src/org/centos/contra/Infra/Utils.groovy
Labels: size/S

#85 Unit test suite
  pom.xml
  test/contra-sample.yml
  test/org/centos/contra/Infra/Utils.groovy
  test/sample-playbook.yml
  test/vars/parseConfig.groovy
Labels: size/XL

#88 FIX catch in createDslContainers
  src/org/centos/contra/Infra/Defaults.groovy
  vars/createDslContainers.groovy
Labels: size/XS

#89 EOS Merge To Master
  pom.xml
  resources/org/centos/contra/Infra/topologyTemplates/beaker.template
  src/org/centos/contra/Infra/Defaults.groovy
  src/org/centos/contra/Infra/Utils.groovy
  test/contra-sample.yml
  test/org/centos/contra/Infra/Utils.groovy
  test/sample-playbook.yml
  test/vars/parseConfig.groovy
  vars/createDslContainers.groovy
Labels: size/XL
